LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := oppo-keyhandler
LOCAL_SRC_FILES := $(call all-java-files-under,src)
LOCAL_MODULE_TAGS := optional
LOCAL_DEX_PREOPT := false

ifeq ($(TARGET_KEYHANDLER_PACKAGE),$(LOCAL_MODULE))
TARGET_KEYHANDLER_TOP_DIR := $(LOCAL_PATH)
TARGET_KEYHANDLER_SRC_FILES := $(LOCAL_SRC_FILES)
endif

include $(BUILD_STATIC_JAVA_LIBRARY)
